"""Sentinel PoC: ``_BEARER_RE`` case-sensitivity drift — RFC 7235 §2.1
auth-scheme case-insensitivity contract violated, letting non-canonical
``BEARER`` / ``bearer`` / ``BeArEr`` Authorization-header fragments slip
past the Bearer-Token detector entirely.

The 2026-05-15 *Secret Scanner Drift Round 13* (WooCommerce + Mailchimp)
closed the e-commerce-platform SMB tier (Shopify Round 12 + WooCommerce
Round 13) and the marketing-email-platform tier (Mailgun Round 12 +
Mailchimp Round 13). The closing-checklist invariant for that round was:

> "Every adjacent-PREFIX candidate gets a ``_KNOWN_TOKENS`` entry, NOT
> just to add issuer-specific attribution but ALSO to anchor detection
> against the entropy-bypass class."

Re-running that audit walker against the *non-issuer-prefixed* detectors
(``_AWS_ID_RE`` / ``_BEARER_RE`` / ``_PEM_RE``) surfaced a previously-
undocumented drift in the Bearer-shape detector: the literal ``Bearer``
in ``_BEARER_RE = re.compile(r"Bearer\\s+([A-Za-z0-9\\-_.]{16,})")`` is
matched case-sensitively, but RFC 7235 §2.1 mandates that the
HTTP auth-scheme component is case-insensitive::

    Each ``challenge`` or ``credentials`` value contains an
    authentication scheme name, followed by parameters [...]. The
    ``auth-scheme`` is **matched case-insensitively** by recipients,
    so a sender that emits ``Bearer xyz`` and one that emits
    ``BEARER xyz`` MUST be treated identically by the receiving
    server.

This makes ``BEARER xyz`` / ``bearer xyz`` / any mixed-case form a
legitimate canonical HTTP Authorization-header shape on the wire.
Real-world emission patterns:

  * **httpie** request log shows ``BEARER`` when the user typed it in
    uppercase via ``--auth-type=bearer --auth=BEARER\\ <tok>``.
  * **curl** with ``--header "Authorization: bearer xyz"`` (lowercase)
    is silently accepted by every modern web framework on the
    receiving side (django-rest-framework, flask-jwt-extended,
    FastAPI's ``OAuth2PasswordBearer``, Starlette, ASP.NET Core,
    Express ``jsonwebtoken``).
  * **YAML/JSON fixtures** generated by automation often canonicalise
    to lowercase or uppercase for consistency with surrounding keys.
  * **Hand-typed examples in documentation / log snippets / hostile
    PR fragments** routinely vary the case.

Threat model
------------

A leaked ``BEARER <body>`` / ``bearer <body>`` / ``BeArEr <body>``
in committed source / log artefacts / CI debug snippets / hostile-PR
fragments fails both Bearer-specific detection branches in
``_scan_content``:

  1. **``_BEARER_RE.finditer(content)``** — pre-fix this regex
     matched only the canonical ``Bearer`` form. ``BEARER xyz`` /
     ``bearer xyz`` / ``BeArEr xyz`` yields zero matches; the
     Bearer-Token attribution (``Bearer-Token wirkt echt``) is lost.

  2. **``_HIGH_ENTROPY_RE.finditer(content)``** — the entropy fallback
     matches the body span as a generic high-entropy hit BUT applies
     ``_looks_like_secret(candidate)`` with
     ``is_assignment=False``, which requires ``min_categories=2``
     (multiple character categories — lowercase + uppercase, or
     lowercase + digit). For **uniform-character-class bodies**
     (all-lowercase legacy / hash-derived tokens, all-uppercase
     UUID-style tokens converted via ``.upper()``, all-digit numeric
     keys), ``_looks_like_secret`` returns ``False`` and the entropy
     fallback emits ZERO findings — the leaked Bearer credential is
     **silently undetected** entirely.

Pre-fix dataflow for the silent-undetection branch:

  - Hostile or accidentally-leaked source carries
    ``"Authorization: bearer abcdefghijklmnopqrstuvwxyz"``
    (24 lowercase chars — a real RSA-256 KID hash, a poorly-seeded
    ``random.choices(ascii_lowercase, k=24)`` test fixture, or a
    hand-typed all-lowercase placeholder that happens to be 24+ chars).
  - ``_BEARER_RE`` (case-sensitive) does NOT match → no Bearer-Token
    finding.
  - ``_HIGH_ENTROPY_RE`` matches the 24-lowercase span, but
    ``_looks_like_secret("abcdefghijklmnopqrstuvwxyz")`` returns
    ``False`` (categories = 1: only lowercase) → no entropy-fallback
    finding.
  - The CI gate passes; the committed credential sits in the public
    repository indefinitely.

Severity
--------

**MEDIUM-HIGH** — detection-from-zero failure for a class of
realistic Bearer-token leaks. The high-severity case is the silent-
undetection branch (uniform-body tokens slip past both detectors);
the attribution-drift branch is medium-severity (the body is still
caught generically, but the Bearer-Token reason that determines
which revocation playbook applies is lost). Mitigated only by the
requirement that the leaked token live alongside a non-canonical
case Bearer literal in the same content blob; in practice this
covers every leak through automation-generated fixtures, lower-case-
normalising loggers, and hostile-PR-introduced fragments that mimic
existing canonical-case detector evasion.

Fix
---

Single-line: add ``(?i)`` inline flag to ``_BEARER_RE``::

    _BEARER_RE = re.compile(r"(?i)Bearer\\s+([A-Za-z0-9\\-_.]{16,})")

The fix has zero false-positive risk for the body capture group:
the body alphabet ``[A-Za-z0-9\\-_.]`` already accepts both cases
of letters, so the inline-flag change only relaxes the matching
of the literal ``Bearer`` keyword. The downstream
``_looks_like_secret(candidate, is_assignment=True)`` heuristic
(``min_categories=1`` in the Bearer path) still filters out
non-secret-looking strings, so a comment like
``"Bearer of bad news, the executive..."`` does not match (no 16+
contiguous chars from ``[A-Za-z0-9\\-_.]`` follow the literal).

Closing-checklist update
------------------------

The non-issuer-prefixed detectors that complement ``_KNOWN_TOKENS``
must inherit the RFC-7235 case-insensitivity contract on the
auth-scheme literal::

  * ``_BEARER_RE`` — Bearer (RFC 6750), THIS round closes.
  * ``_AWS_ID_RE`` — uppercase by AWS spec (``AKIA`` / ``ASIA`` /
    ``ACCA``), no case-insensitivity needed; the AWS docs canonicalise
    to uppercase only.
  * ``_PEM_RE`` — PEM markers are uppercase by RFC 7468 §2; no case-
    insensitivity needed.

Future detectors for additional auth-scheme literals (``Basic`` /
``Digest`` / ``Negotiate`` from RFC 7617 / 7616 / 4559, ``Token``
from GitHub's older API style, ``HOBA`` from RFC 7486) must
similarly inherit the ``(?i)`` flag at the auth-scheme literal.

Inventory invariant
-------------------

The PoC inventory test below names every auth-scheme literal currently
matched anywhere in the project's detectors and asserts the
case-insensitivity contract holds — a future regression to the
case-sensitive shape (or a new auth-scheme literal added without the
``(?i)`` flag) fails the test until the canonical shape is restored.

Marker: SENTINEL_BEARER_CASE_DRIFT.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from src.utils.secret_scanner import scan_repository


SENTINEL_BEARER_CASE_DRIFT = "rfc-7235 auth-scheme case-insensitivity drift"


# Token bodies designed to exercise each detection branch:
#
#  * MIXED_BODY: passes both ``_BEARER_RE`` + ``_looks_like_secret`` AND
#    the entropy fallback. Pre-fix the attribution is "Bearer-Token wirkt
#    echt" for canonical case, "Hochentropischer Token-String" for non-
#    canonical case (attribution drift only).
#  * LOWERCASE_BODY: passes ``_BEARER_RE`` + ``_looks_like_secret``
#    (assignment mode allows 1 category) but FAILS the entropy fallback's
#    ``_looks_like_secret(is_assignment=False)`` because categories=1.
#    Pre-fix non-canonical case yields ZERO findings (silent
#    undetection).
#  * UPPERCASE_BODY: identical to LOWERCASE_BODY shape, single category.
#  * DIGIT_BODY: identical shape, single digit category.

_MIXED_BODY = "AbCdEfGhIjKlMnOpQrStUvWx0123"  # mixed-case + digits = 3 categories
_LOWERCASE_BODY = "abcdefghijklmnopqrstuvwxyz"  # 26 chars, 1 category
_UPPERCASE_BODY = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"  # 26 chars, 1 category
_DIGIT_BODY = "0123456789012345678901234"      # 25 chars, 1 category, repeats


# ---------------------------------------------------------------------------
# (1) Case-insensitivity PoCs: every non-canonical Bearer form yields the
#     Bearer-Token-specific finding.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "scheme",
    [
        "bearer",   # all-lowercase (curl default)
        "BEARER",   # all-uppercase (httpie debug log)
        "BeArEr",   # mixed-case (hostile-PR-style obfuscation)
        "bEaReR",   # mixed-case alternate
        "Bearer",   # canonical (regression guard)
    ],
)
def test_secret_scanner_detects_bearer_case_insensitive_mixed_body(
    tmp_path: Path, scheme: str
) -> None:
    """Every case variation of the Bearer auth-scheme literal must be
    detected with the Bearer-Token-specific attribution, per RFC 7235
    §2.1's case-insensitive auth-scheme contract.

    The mixed-body case proves the attribution-drift branch closes:
    pre-fix non-canonical cases lost the issuer attribution (only the
    generic entropy reason landed); post-fix every case yields the
    Bearer-Token-specific reason.
    """
    file_path = tmp_path / "header_log.txt"
    file_path.write_text(
        f"Authorization: {scheme} {_MIXED_BODY}\n", encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])

    reasons = [f.reason for f in findings]
    assert "Bearer-Token wirkt echt" in reasons, (
        f"Bearer detector lost attribution for non-canonical "
        f"case {scheme!r}; got reasons {reasons!r}. "
        f"RFC 7235 §2.1 says auth-scheme is case-insensitive; the leaked "
        f"token must yield the Bearer-Token-specific reason regardless of "
        f"case. ({SENTINEL_BEARER_CASE_DRIFT})"
    )
    # Confirm raw secret never appears in findings (redaction contract).
    assert _MIXED_BODY not in [f.match for f in findings]


# ---------------------------------------------------------------------------
# (2) Silent-undetection PoCs: uniform-character-class bodies bypass the
#     entropy fallback entirely, so the case-insensitive Bearer detector
#     is the ONLY branch that catches them.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "scheme",
    [
        "bearer",   # all-lowercase
        "BEARER",   # all-uppercase
        "BeArEr",   # mixed-case obfuscation
        "Bearer",   # canonical regression guard
    ],
)
@pytest.mark.parametrize(
    "body,body_label",
    [
        (_LOWERCASE_BODY, "lowercase"),
        (_UPPERCASE_BODY, "uppercase"),
        (_DIGIT_BODY, "digit"),
    ],
)
def test_secret_scanner_detects_bearer_uniform_body_with_case_variants(
    tmp_path: Path, scheme: str, body: str, body_label: str
) -> None:
    """Uniform-character-class bodies (all-lowercase / all-uppercase /
    all-digit) bypass ``_HIGH_ENTROPY_RE``'s ``_looks_like_secret``
    heuristic (which requires ``min_categories=2`` in non-assignment
    mode). The case-insensitive Bearer detector is the ONLY detection
    branch that catches these — pre-fix non-canonical case +
    uniform body = SILENT UNDETECTION.

    Post-fix every (scheme × body) combination yields the
    Bearer-Token-specific finding.
    """
    file_path = tmp_path / "auth_fixture.json"
    file_path.write_text(
        f'{{"authorization": "{scheme} {body}"}}\n', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])

    reasons = [f.reason for f in findings]
    assert "Bearer-Token wirkt echt" in reasons, (
        f"SILENT UNDETECTION: scheme={scheme!r}, body_class={body_label!r}, "
        f"body={body!r}; got reasons {reasons!r}. "
        f"This is the high-severity branch — without the Bearer-Token "
        f"detection the uniform-body token slips past BOTH detectors "
        f"and the credential sits committed indefinitely. "
        f"({SENTINEL_BEARER_CASE_DRIFT})"
    )


# ---------------------------------------------------------------------------
# (3) Negative cases: ensure the case-insensitive change does NOT introduce
#     false-positive matches on natural-language text that mentions
#     "bearer" / "BEARER" without a token-shaped body.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        # No 16+ contiguous chars from [A-Za-z0-9\-_.] after the keyword.
        "The bearer of bad news is rarely welcome.",
        "BEARER must be honoured per the contract.",
        "Bearer responsibility falls to the manager.",
        # Whitespace inside the would-be token body breaks the regex.
        "bearer short token here only",
        # Punctuation immediately after "Bearer" breaks \\s+ requirement.
        "bearer,xyz",
        "BEARER!",
    ],
)
def test_secret_scanner_no_false_positives_on_natural_bearer_text(
    tmp_path: Path, text: str
) -> None:
    """The case-insensitive ``_BEARER_RE`` must NOT match natural-language
    sentences that mention "bearer" without a 16+-char token-shaped body
    following. The body alphabet ``[A-Za-z0-9\\-_.]{16,}`` is the
    structural disambiguator — English sentences embed spaces, so no 16+
    contiguous match is possible.
    """
    file_path = tmp_path / "natural_text.md"
    file_path.write_text(f"{text}\n", encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])

    bearer_findings = [f for f in findings if f.reason == "Bearer-Token wirkt echt"]
    assert not bearer_findings, (
        f"False-positive Bearer-Token finding for natural-language text "
        f"{text!r}. The detector should require 16+ contiguous chars from "
        f"the body alphabet. ({SENTINEL_BEARER_CASE_DRIFT})"
    )


# ---------------------------------------------------------------------------
# (4) Regression guard: canonical-case Bearer continues to be detected
#     with the canonical attribution (no regression in the existing
#     detection path).
# ---------------------------------------------------------------------------


def test_secret_scanner_canonical_bearer_regression_guard(tmp_path: Path) -> None:
    """The canonical ``Bearer <body>`` form continues to fire the
    Bearer-Token detector with mixed-case body content. Regression
    guard against any future change that breaks the canonical path
    via overzealous tightening."""
    file_path = tmp_path / "canonical.py"
    file_path.write_text(
        f'HEADERS = {{"Authorization": "Bearer {_MIXED_BODY}"}}\n',
        encoding="utf-8",
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Bearer-Token wirkt echt" in reasons


# ---------------------------------------------------------------------------
# (5) Compiled-regex invariant: ``_BEARER_RE`` flags include
#     ``re.IGNORECASE`` (programmatic pin against future drift back to
#     the case-sensitive shape).
# ---------------------------------------------------------------------------


def test_bearer_re_flags_include_ignorecase() -> None:
    """The compiled ``_BEARER_RE`` must carry the ``re.IGNORECASE`` flag
    so the auth-scheme literal is matched per the RFC 7235 §2.1
    case-insensitive contract. A future regression that reverts to the
    case-sensitive ``re.compile(r"Bearer\\s+...")`` shape fails this
    invariant immediately."""
    import re as _re

    from src.utils.secret_scanner import _BEARER_RE

    assert _BEARER_RE.flags & _re.IGNORECASE, (
        f"_BEARER_RE flags={_BEARER_RE.flags!r} missing re.IGNORECASE. "
        f"RFC 7235 §2.1 requires case-insensitive matching on the "
        f"Bearer auth-scheme literal. ({SENTINEL_BEARER_CASE_DRIFT})"
    )


# ---------------------------------------------------------------------------
# (6) End-to-end ``Authorization:`` header inventory: the case-insensitive
#     fix must cover the common header-emission shapes wholesale.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "raw_header,case_label",
    [
        # HTTP-style log line shapes (curl -v, requests --debug, ngrep)
        (f"> Authorization: bearer {_MIXED_BODY}", "lowercase-curl-debug"),
        (f"< Authorization: BEARER {_MIXED_BODY}", "uppercase-curl-debug"),
        (f"Authorization: BeArEr {_MIXED_BODY}", "mixed-case-fixture"),
        # Python-dict / JSON fixture shapes
        (f'{{"Authorization": "bearer {_MIXED_BODY}"}}', "json-lowercase"),
        (f"{{'Authorization': 'BEARER {_MIXED_BODY}'}}", "py-dict-uppercase"),
        # YAML fixture shape (single-quoted)
        (f"authorization: 'bearer {_MIXED_BODY}'", "yaml-lowercase"),
    ],
)
def test_secret_scanner_detects_bearer_across_emission_shapes(
    tmp_path: Path, raw_header: str, case_label: str
) -> None:
    """Real-world Bearer emission shapes (curl debug logs, JSON fixtures,
    YAML config, Python dicts) all canonicalise the case differently
    depending on the emitter; the detector must cover them wholesale."""
    file_path = tmp_path / f"fixture_{case_label}.txt"
    file_path.write_text(f"{raw_header}\n", encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])

    reasons = [f.reason for f in findings]
    assert "Bearer-Token wirkt echt" in reasons, (
        f"Bearer detector missed emission shape {case_label!r}: "
        f"{raw_header!r}; got reasons {reasons!r}. "
        f"({SENTINEL_BEARER_CASE_DRIFT})"
    )


# ---------------------------------------------------------------------------
# (7) Masking-contract test: the detected Bearer body is redacted in the
#     finding's ``match`` attribute, regardless of case.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "scheme",
    ["bearer", "BEARER", "BeArEr", "Bearer"],
)
def test_secret_scanner_bearer_masks_body_across_cases(
    tmp_path: Path, scheme: str
) -> None:
    """Pin the masking contract: the raw token body never appears in
    the finding's ``match`` field, regardless of the Bearer literal's
    case. Mirrors the per-issuer masking-contract tests in the
    Round 12 / Round 13 PRs."""
    file_path = tmp_path / "mask_test.py"
    file_path.write_text(
        f'AUTH = "{scheme} {_MIXED_BODY}"\n', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    bearer_findings = [f for f in findings if f.reason == "Bearer-Token wirkt echt"]

    assert bearer_findings, (
        f"No Bearer-Token finding for scheme={scheme!r}; cannot test "
        f"masking. ({SENTINEL_BEARER_CASE_DRIFT})"
    )

    for finding in bearer_findings:
        assert finding.match != _MIXED_BODY, (
            f"Raw token body leaked verbatim in finding.match={finding.match!r}; "
            f"_mask_secret contract broken for scheme={scheme!r}. "
            f"({SENTINEL_BEARER_CASE_DRIFT})"
        )
        # The masked form keeps a short prefix + suffix per _mask_secret.
        assert "***" in finding.match


# ---------------------------------------------------------------------------
# (8) Cross-vendor boundary regression: ``_BEARER_RE`` does NOT collide
#     with any ``_KNOWN_TOKENS`` issuer-specific pattern. The known-tokens
#     loop runs BEFORE ``_BEARER_RE`` in ``_scan_content``, so a JWT
#     embedded in a Bearer header should yield the JWT-specific reason
#     (not the generic Bearer-Token reason).
# ---------------------------------------------------------------------------


def test_secret_scanner_jwt_in_lowercase_bearer_still_yields_jwt_reason(
    tmp_path: Path,
) -> None:
    """Cross-validation: a JWT in a lowercase ``bearer`` header must
    yield the JWT-specific attribution (matched first via
    ``_KNOWN_TOKENS``), with the generic Bearer-Token reason absent
    for that span. The case-insensitive ``_BEARER_RE`` change does NOT
    perturb the issuer-specific JWT matching that runs earlier in the
    detector ordering."""
    file_path = tmp_path / "jwt_log.txt"
    # Synthetic format-correct JWT shape (header.payload.signature).
    jwt = (
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        "."
        "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlRlc3QiLCJpYXQiOjE1MTYyMzkwMjJ9"
        "."
        "SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
    )
    file_path.write_text(f"Authorization: bearer {jwt}\n", encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]

    assert "JSON Web Token (JWT) gefunden" in reasons, (
        f"JWT detector must fire on JWT-shape token regardless of "
        f"Bearer case; got reasons {reasons!r}. "
        f"({SENTINEL_BEARER_CASE_DRIFT})"
    )
