"""Sentinel PoC: secret-scanner drift Round 13 — closes the
**adjacent-prefix candidates named-but-deferred by Round 12**: WooCommerce
REST API consumer keys / consumer secrets (``ck_<32+ alphanumeric>`` /
``cs_<32+ alphanumeric>``) and Mailchimp API keys (``<32 hex>-us<region>``).

Round 12 (PR closing Mailgun + Square + the Shopify access-token family)
closed the **e-commerce-platform** sub-landscape via the four Shopify
prefixes and explicitly named six named-but-deferred next-round targets:

  1. **Magento 2 admin integration token** (``Bearer <40 hex>`` — no
     canonical prefix, bucket-(b) shape, covered structurally by the
     entropy fallback). Cannot anchor issuer-specific attribution.
  2. **BigCommerce API token** (``<32-64 base64url>`` — no canonical
     prefix, bucket-(b) shape). Same.
  3. **WooCommerce REST API key** (``ck_<32 alphanumeric>`` +
     ``cs_<32 alphanumeric>`` pair — adjacent **PREFIX** candidate;
     anchors against the prefix for specific attribution).
  4. **Mailchimp API key** (``<32 hex>-us<region>`` — adjacent
     **PREFIX** candidate, with the ``-us<digit>`` region suffix as
     the structural disambiguator).
  5. **SES SMTP credentials** (no canonical prefix, bucket-(b)).
  6. **Postmark API key** (``<UUID-shape>`` — no canonical prefix,
     bucket-(b)).

Targets (1), (2), (5), (6) are bucket-(b) (no prefix, structural-only
detection via entropy fallback) — they cannot anchor specific
attribution and are deferred indefinitely. Targets (3) and (4) are the
adjacent-PREFIX candidates this round closes via canonical issuer-
specific patterns.

  1. **WooCommerce REST API Consumer Key** (``ck_<32+ alphanumeric>``):
     issued via wp-admin > WooCommerce > Settings > Advanced > REST API
     > Add Key. The body is generated by ``wp_generate_password(32,
     false)`` in modern WooCommerce (32 chars from ``[a-zA-Z0-9]``);
     legacy installations using ``wc_rand_hash()`` produced 64-char
     lowercase-hex bodies; intermediate versions used 40-char
     alphanumeric bodies. The ``{32,}`` lower bound covers the modern
     canonical form AND every documented legacy variant in one regex.
     A leak paired with the matching ``cs_`` grants the issuing API
     user's full WooCommerce REST scope: read/write every product,
     order, customer, coupon, refund, shipping zone, tax rate, and
     webhook configuration; the role attached to the API user
     (read / write / read_write) determines effective blast radius
     but write-tier keys are the documented default. Pre-fix every
     ``ck_`` token with a uniform character class body was SILENTLY
     UNDETECTED — the entropy fallback's ``_looks_like_secret``
     heuristic requires multiple character categories, and a body
     like ``ck_aaaaaa...`` failed that check entirely; mixed-case
     bodies were caught only by the generic "Verdächtige Zuweisung"
     assignment heuristic (depends on the variable name carrying a
     sensitive keyword), losing the WooCommerce-specific attribution.

  2. **WooCommerce REST API Consumer Secret** (``cs_<32+
     alphanumeric>``): sibling to ``ck_`` — issued together by the
     same admin flow, used together as Basic Auth ``ck_<key>:cs_<
     secret>`` for every WooCommerce REST API request. Same body
     shape as ``ck_`` (3-char prefix + 32+ char alphanumeric body).
     A leak of the consumer secret alone is less immediately
     exploitable (the key is the identifier, the secret is the
     signing material), but standard WooCommerce documentation
     recommends storing both in the same config block — a leak of
     either typically implies a leak of both, and a leaked ``cs_``
     strongly signals that a ``ck_`` exists somewhere in the same
     repo. Distinct reason from the consumer key so the report
     calls out *which* half of the credential pair leaked.

  3. **Mailchimp API Key** (``<32 hex>-us<datacenter>``): issued via
     mailchimp.com/account/api-keys. Format: 32 lowercase hex chars +
     literal ``-us`` + 1-3 digit datacenter number (``-us1``,
     ``-us14``, ``-us20`` are all valid; the datacenter shard is
     assigned at account creation based on geographic region). The
     ``-us<N>`` suffix is the structural disambiguator: the entropy
     fallback's ``[A-Za-z0-9+/=_-]{24,}`` regex matches the entire
     string (every char in the alphabet, including the dash), but the
     ``-us<digit>`` suffix is unique to Mailchimp's datacenter
     routing convention and unambiguously identifies the issuer. A
     leak grants the issuing account's full Mailchimp scope: audience
     / list / contact / campaign / automation read+write; export the
     full subscriber CSV (PII exfiltration); send mass mailings AS
     the account (phishing amplification leveraging the account's
     authenticated sender domain and existing SPF/DKIM/DMARC
     reputation); modify webhook URLs to redirect events to
     attacker-controlled endpoints; create new transactional API
     keys via Mandrill for persistence. Pre-fix the entropy fallback
     matched the full ``<body>-us<N>`` span as a single generic
     ``Hochentropischer Token-String`` finding, losing the
     Mailchimp-specific attribution.

Each test below pre-fix would have flagged only the generic high-
entropy fallback (or "Verdächtige Zuweisung" for the WC keys with
mixed-case bodies); post-fix every token gets the issuer-specific
reason that incident-response playbooks key off (rotation flow,
revocation URL, blast-radius estimate).

Closing-checklist sweep status post-Round-13:

  * **Adjacent-prefix candidates from Round 12:** WooCommerce
    (named, closed); Mailchimp (named, closed). The remaining four
    Round-12 named candidates (Magento 2 admin integration token,
    BigCommerce API token, SES SMTP credentials, Postmark API key)
    are bucket-(b) (no canonical prefix) and are deferred indefinitely
    — they cannot anchor issuer attribution and are caught structurally
    by the entropy fallback.
  * **E-commerce-platform tier expanded:** Shopify family (4 prefixes,
    Round 12) + WooCommerce (2 prefixes, Round 13) = 6 of 6 documented
    e-commerce SMB-tier prefixes enumerated. Magento (enterprise tier)
    and BigCommerce (SMB tier) remain bucket-(b) and are not anchorable.
  * **Marketing-email-platform tier (Mailgun Round 12 +
    Mailchimp Round 13) now covers the two highest-volume vendors**
    — both grant full mass-mail / contact-list exfiltration / webhook
    redirection scope but their control planes are distinct
    (app.mailgun.com vs. mailchimp.com/account/api/), so per-issuer
    attribution is critical for IR triage.
  * **Named-but-deferred next-round candidates:** Magento 2 admin
    integration token (``Bearer <40 hex>`` — no canonical prefix,
    bucket-(b)); BigCommerce API token (``<32-64 base64url>`` — no
    canonical prefix, bucket-(b)); SES SMTP credentials (no canonical
    prefix, bucket-(b)); Postmark API key (``<UUID-shape>`` — no
    canonical prefix, bucket-(b)); Algolia Admin API key (``<32 hex>``
    with embedded ``application_id`` parameter — adjacent context
    candidate, deferred pending application_id-aware extraction);
    Pinecone API key (``<UUID-shape>`` — bucket-(b)).
"""

from __future__ import annotations

from pathlib import Path

from src.utils.secret_scanner import scan_repository


# ---------------------------------------------------------------------------
# 1. WooCommerce Consumer Key (``ck_<32+ alphanumeric>``)
# ---------------------------------------------------------------------------
#
# Format: ``ck_<32+ alphanumeric chars>``. Issued via wp-admin >
# WooCommerce > Settings > Advanced > REST API > Add Key. Body
# generated by ``wp_generate_password(32, false)`` for modern WC; 40
# chars for intermediate versions; 64-char lowercase hex for legacy.


def test_secret_scanner_detects_woocommerce_consumer_key(tmp_path: Path) -> None:
    """WooCommerce Consumer Key: ``ck_<32 alphanumeric>``.

    Pre-fix every ``ck_`` token with a uniform character class body
    was SILENTLY UNDETECTED — the entropy fallback's
    ``_looks_like_secret`` heuristic requires multiple character
    categories, and a body like ``ck_aaaaaa...`` failed that check
    entirely. Mixed-case bodies were caught only by the generic
    "Verdächtige Zuweisung" assignment heuristic (depends on the
    variable name carrying a sensitive keyword), losing the
    WooCommerce-specific attribution that incident-response keys off
    (revocation at wp-admin > WooCommerce > Settings > Advanced >
    REST API).
    """
    file_path = tmp_path / "woocommerce_config.py"
    body = "a" * 32  # 32-char uniform body (silently undetected pre-fix)
    secret = f"ck_{body}"
    assert len(body) == 32
    file_path.write_text(
        f'WC_CONSUMER_KEY = "{secret}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])

    assert findings, "Should detect WooCommerce Consumer Key"
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" in reasons, (
        f"Expected WooCommerce-specific attribution, got reasons: "
        f"{reasons}. WooCommerce Consumer Keys (paired with the matching "
        "cs_ secret) grant the issuing API user's full WooCommerce REST "
        "scope (product / order / customer / coupon / refund / shipping "
        "/ tax / webhook read+write); precise attribution accelerates "
        "revocation at wp-admin > WooCommerce > Settings > Advanced > "
        "REST API."
    )
    # Mask check: raw value must not leak.
    assert secret not in [f.match for f in findings]


def test_woocommerce_consumer_key_detected_in_env_config(tmp_path: Path) -> None:
    """WooCommerce keys commonly appear in ``.env`` / shell-rc files
    when an operator wires the REST API credentials into a background
    importer / sync job. The detector must work in unquoted
    ``KEY=VALUE`` shapes."""
    file_path = tmp_path / "wc.env"
    body = "aA1bB2cC3dD4eE5fF6gG7hH8iI9jJ0kK"  # 32 mixed alphanumeric
    secret = f"ck_{body}"
    assert len(body) == 32
    file_path.write_text(f"WC_CONSUMER_KEY={secret}\n", encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" in reasons, (
        "WooCommerce detector must flag keys in unquoted KEY=VALUE shapes"
    )


def test_woocommerce_consumer_key_legacy_64_hex(tmp_path: Path) -> None:
    """Legacy WooCommerce installations using ``wc_rand_hash()``
    produce 64-char lowercase-hex bodies. The ``{32,}`` lower bound
    covers the modern 32-char form AND every documented legacy
    variant in one regex; the greedy quantifier + lookahead anchor
    end at the natural alphanumeric boundary so the longest
    legitimate body wins."""
    file_path = tmp_path / "wc_legacy.py"
    body = "0123456789abcdef" * 4  # 64 lowercase hex
    secret = f"ck_{body}"
    assert len(body) == 64
    file_path.write_text(
        f'LEGACY_WC_KEY = "{secret}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" in reasons


def test_woocommerce_consumer_key_does_not_flag_short_ck_prefix(
    tmp_path: Path,
) -> None:
    """Negative case: short ``ck_`` strings MUST NOT match the
    WooCommerce pattern. The strict 32-char alphanumeric body length
    guard prevents collision with operator-named placeholders
    (``ck_callback``, ``ck_button``, ``track_id`` — the latter is
    blocked by the lookbehind anchor) and accidentally-truncated
    tokens.
    """
    file_path = tmp_path / "config.py"
    not_wc = "ck_callback"
    file_path.write_text(f'placeholder = "{not_wc}"', encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" not in reasons


def test_woocommerce_consumer_key_lookbehind_anchor(tmp_path: Path) -> None:
    """Negative case: ``track_<body>`` MUST NOT match the WooCommerce
    ``ck_`` pattern. The ``(?<![A-Za-z0-9])`` lookbehind anchor ensures
    the ``ck_`` prefix is not preceded by an alphanumeric character
    that would make it part of a larger identifier (e.g. ``track_id``,
    ``check_value``, ``stack_trace`` — these are normal English words
    that contain ``ck_`` as a substring)."""
    file_path = tmp_path / "config.py"
    body = "a" * 32
    not_wc = f"track_{body}"  # Has ``ck_`` as substring of ``track_``
    file_path.write_text(
        f'something = "{not_wc}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" not in reasons


# ---------------------------------------------------------------------------
# 2. WooCommerce Consumer Secret (``cs_<32+ alphanumeric>``)
# ---------------------------------------------------------------------------
#
# Format: ``cs_<32+ alphanumeric chars>``. Sibling to ``ck_`` —
# issued together by the same admin flow, used together as Basic
# Auth ``ck_<key>:cs_<secret>`` for every WooCommerce REST request.


def test_secret_scanner_detects_woocommerce_consumer_secret(tmp_path: Path) -> None:
    """WooCommerce Consumer Secret: ``cs_<32 alphanumeric>``.

    Pre-fix detection gap identical to ``ck_``: silently undetected
    for uniform-character-class bodies, generic "Verdächtige
    Zuweisung" only for mixed-case bodies in env-shaped assignments.
    Distinct reason from the consumer key so the report identifies
    *which* half of the credential pair leaked.
    """
    file_path = tmp_path / "woocommerce_config.py"
    body = "b" * 32  # 32-char uniform body
    secret = f"cs_{body}"
    file_path.write_text(
        f'WC_CONSUMER_SECRET = "{secret}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])

    assert findings, "Should detect WooCommerce Consumer Secret"
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Secret gefunden" in reasons, (
        f"Expected WooCommerce-Consumer-Secret-specific attribution, "
        f"got reasons: {reasons}. WooCommerce Consumer Secrets are the "
        "signing half of the REST API Basic Auth pair; a leak signals "
        "that the matching ``ck_`` is also at risk."
    )
    assert secret not in [f.match for f in findings]


def test_woocommerce_consumer_secret_does_not_flag_short_cs_prefix(
    tmp_path: Path,
) -> None:
    """Negative case: short ``cs_`` strings MUST NOT match the
    WooCommerce pattern. The strict 32-char body length guard prevents
    collision with operator-named placeholders (``cs_button``,
    ``cs_value``, ``docs_url``)."""
    file_path = tmp_path / "config.py"
    not_wc = "cs_helper"
    file_path.write_text(f'placeholder = "{not_wc}"', encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Secret gefunden" not in reasons


def test_woocommerce_credential_pair_both_detected(tmp_path: Path) -> None:
    """When both ``ck_`` and ``cs_`` appear in the same file (the
    canonical WooCommerce config shape — both halves stored in the
    same secrets block), each gets its own distinct attribution
    line in the findings list. This lets the operator confirm *both*
    halves of the credential pair need to be rotated."""
    file_path = tmp_path / "wc_pair.py"
    ck_body = "a" * 32
    cs_body = "b" * 32
    ck = f"ck_{ck_body}"
    cs = f"cs_{cs_body}"
    file_path.write_text(
        f'WC_CONSUMER_KEY = "{ck}"\n'
        f'WC_CONSUMER_SECRET = "{cs}"\n',
        encoding="utf-8",
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "WooCommerce Consumer Key gefunden" in reasons
    assert "WooCommerce Consumer Secret gefunden" in reasons


# ---------------------------------------------------------------------------
# 3. Mailchimp API Key (``<32 hex>-us<region>``)
# ---------------------------------------------------------------------------
#
# Format: ``<32 lowercase hex>-us<datacenter>``. Issued via
# mailchimp.com/account/api-keys. The ``-us<N>`` suffix is unique to
# Mailchimp's datacenter routing convention and unambiguously
# identifies the issuer; no other major API vendor uses this suffix
# pattern.


def test_secret_scanner_detects_mailchimp_api_key(tmp_path: Path) -> None:
    """Mailchimp API Key: ``<32 hex>-us<datacenter>``.

    Pre-fix the entropy fallback ``[A-Za-z0-9+/=_-]{24,}`` matched
    the full ``<body>-us<N>`` span (the dash IS in the entropy
    alphabet) as a single generic ``Hochentropischer Token-String``
    finding, losing the Mailchimp-specific attribution that
    incident-response keys off (revocation at
    mailchimp.com/account/api/).
    """
    file_path = tmp_path / "mailchimp_config.py"
    body = "0" * 32
    secret = f"{body}-us6"
    assert len(body) == 32
    file_path.write_text(
        f'MAILCHIMP_API_KEY = "{secret}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])

    assert findings, "Should detect Mailchimp API Key"
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" in reasons, (
        f"Expected Mailchimp-specific attribution, got reasons: "
        f"{reasons}. Mailchimp API keys grant the issuing account's "
        "full Mailchimp scope (audience / contact / campaign / "
        "automation read+write; PII exfiltration of the subscriber "
        "CSV; phishing amplification via the account's authenticated "
        "sender domain); precise attribution accelerates revocation "
        "at mailchimp.com/account/api/."
    )
    # Mask check: raw value must not leak.
    assert secret not in [f.match for f in findings]


def test_mailchimp_api_key_detected_in_env_config(tmp_path: Path) -> None:
    """Mailchimp keys commonly appear in ``.env`` files when the
    operator wires the API key into a contact-sync / campaign-trigger
    automation. The detector must work in unquoted ``KEY=VALUE``
    shapes."""
    file_path = tmp_path / "mailchimp.env"
    body = "abcdef0123456789abcdef0123456789"  # 32 hex
    secret = f"{body}-us14"
    file_path.write_text(f"MAILCHIMP_KEY={secret}\n", encoding="utf-8")

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" in reasons, (
        "Mailchimp detector must flag keys in unquoted KEY=VALUE shapes"
    )


def test_mailchimp_api_key_supports_three_digit_datacenter(
    tmp_path: Path,
) -> None:
    """Mailchimp datacenter numbers grow over time as the platform
    adds capacity. Accept 1-3 digit values (``-us1``, ``-us14``,
    ``-us100``) — the ``[0-9]{1,3}`` bound matches every documented
    datacenter shard."""
    file_path = tmp_path / "mailchimp_large.py"
    body = "fedcba9876543210fedcba9876543210"
    secret = f"{body}-us100"
    file_path.write_text(
        f'KEY = "{secret}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" in reasons


def test_mailchimp_api_key_rejects_non_hex_body(tmp_path: Path) -> None:
    """Negative case: ``<32 chars>-usN`` where the body has non-hex
    chars (uppercase letters, ``g-z``) MUST NOT match the Mailchimp
    pattern. Mailchimp's canonical format is strictly 32 lowercase
    hex chars; matching a broader alphabet would collide with
    arbitrary operator-supplied strings that happen to end in
    ``-us<digit>``."""
    file_path = tmp_path / "config.py"
    not_mailchimp = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-us6"  # uppercase X
    file_path.write_text(
        f'placeholder = "{not_mailchimp}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" not in reasons


def test_mailchimp_api_key_rejects_short_body(tmp_path: Path) -> None:
    """Negative case: ``<short hex>-usN`` MUST NOT match the
    Mailchimp pattern. The strict 32-hex body length guard prevents
    collision with shorter hex strings that happen to be followed
    by ``-us<digit>`` (e.g. a git short SHA followed by a CI run
    suffix)."""
    file_path = tmp_path / "config.py"
    short_body = "0123456789abcdef"  # only 16 hex chars
    not_mailchimp = f"{short_body}-us6"
    file_path.write_text(
        f'placeholder = "{not_mailchimp}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" not in reasons


def test_mailchimp_api_key_rejects_wrong_suffix(tmp_path: Path) -> None:
    """Negative case: ``<32 hex>-eu1`` MUST NOT match the Mailchimp
    pattern. The ``-us<digit>`` suffix is the structural
    disambiguator; other shapes (``-eu1`` for European DCs in some
    products, ``-de2`` for German DCs) belong to different vendors'
    schemas. Mailchimp specifically uses the ``-us<digit>``
    convention exclusively per their documented routing scheme."""
    file_path = tmp_path / "config.py"
    body = "0123456789abcdef0123456789abcdef"
    not_mailchimp = f"{body}-eu1"  # Wrong region prefix
    file_path.write_text(
        f'placeholder = "{not_mailchimp}"', encoding="utf-8"
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]
    assert "Mailchimp API Key gefunden" not in reasons


# ---------------------------------------------------------------------------
# 4. Cross-vendor boundary regression
# ---------------------------------------------------------------------------


def test_round13_patterns_do_not_collide_with_existing_vendors(
    tmp_path: Path,
) -> None:
    """The three Round-13 issuers (WooCommerce ``ck_``, WooCommerce
    ``cs_``, Mailchimp ``<hex>-us<N>``) MUST NOT cross-trigger any
    existing vendor's pattern:

      * WooCommerce ``ck_`` vs. Stripe ``sk_``/``rk_``/``whsec_``:
        different prefix shape (``ck_`` vs. ``sk_`` etc.).
      * WooCommerce ``cs_`` vs. Shopify ``shpss_``/``shppa_``/etc.:
        Shopify prefixes are all 6+ chars (``shpat_`` etc.); WC
        ``cs_`` is 3 chars + body and the body alphabets differ
        (WC uses ``[a-zA-Z0-9]``; Shopify uses ``[a-fA-F0-9]``).
      * Mailchimp ``<hex>-us<N>`` vs. Mailgun ``key-<hex>``: both
        marketing-email-platform vendors, but the prefix is opposite
        (Mailgun's is at the start of the token; Mailchimp's
        ``-us<N>`` is at the end as a suffix), and the body alphabets
        differ slightly.
    """
    file_path = tmp_path / "mixed_round13.py"
    wc_ck = f"ck_{'a' * 32}"
    wc_cs = f"cs_{'b' * 32}"
    mailchimp = f"{'0' * 32}-us6"
    file_path.write_text(
        f'WC_CK = "{wc_ck}"\n'
        f'WC_CS = "{wc_cs}"\n'
        f'MAILCHIMP = "{mailchimp}"\n',
        encoding="utf-8",
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    reasons = [f.reason for f in findings]

    assert "WooCommerce Consumer Key gefunden" in reasons
    assert "WooCommerce Consumer Secret gefunden" in reasons
    assert "Mailchimp API Key gefunden" in reasons

    # No cross-vendor false positives.
    assert "Stripe Live Secret Key gefunden" not in reasons
    assert "Stripe Test Secret Key gefunden" not in reasons
    assert "Stripe Webhook Signing Secret gefunden" not in reasons
    assert "Shopify Shared Secret gefunden" not in reasons
    assert "Mailgun Private API Key gefunden" not in reasons


def test_round13_secrets_are_masked_in_findings(tmp_path: Path) -> None:
    """All Round-13 secret matches must be masked via ``_mask_secret``
    before reporting, so an accidental commit of the scan output does
    NOT leak the underlying token bytes verbatim to subsequent
    consumers (CI logs, alert pages, PR comments). Mirrors the
    masking contract from every prior round's tests."""
    file_path = tmp_path / "round13_mix.py"
    wc_ck = f"ck_{'a' * 32}"
    wc_cs = f"cs_{'b' * 32}"
    mailchimp = f"{'c' * 32}-us6"
    file_path.write_text(
        f'WC_CK = "{wc_ck}"\n'
        f'WC_CS = "{wc_cs}"\n'
        f'MAILCHIMP = "{mailchimp}"\n',
        encoding="utf-8",
    )

    findings = scan_repository(tmp_path, paths=[file_path])
    matches = [f.match for f in findings]

    # Verbatim tokens must NOT appear in any finding.match span.
    for secret in (wc_ck, wc_cs, mailchimp):
        assert secret not in matches, (
            f"Round-13 secret {secret!r} leaked verbatim into findings; "
            f"_mask_secret must redact every secret match."
        )
