"""Shared default values for configuration and tooling."""

from __future__ import annotations

from pathlib import Path

__all__ = [
    "DEFAULT_OUT_PATH",
    "DEFAULT_FEED_HEALTH_PATH",
    "DEFAULT_FEED_HEALTH_JSON_PATH",
    "DEFAULT_FEED_TITLE",
    "DEFAULT_FEED_DESCRIPTION",
    "DEFAULT_FEED_LINK",
    "DEFAULT_FEED_TTL_MINUTES",
    "DEFAULT_DESCRIPTION_CHAR_LIMIT",
    "DEFAULT_FRESH_PUBDATE_WINDOW_MIN",
    "DEFAULT_MAX_ITEMS",
    "DEFAULT_MAX_ITEM_AGE_DAYS",
    "DEFAULT_ABSOLUTE_MAX_ITEM_AGE_DAYS",
    "DEFAULT_ENDS_AT_GRACE_MINUTES",
    "DEFAULT_CACHE_MAX_AGE_HOURS",
    "DEFAULT_PROVIDER_TIMEOUT",
    "DEFAULT_PROVIDER_MAX_WORKERS",
    "DEFAULT_STATE_PATH",
    "DEFAULT_STATE_RETENTION_DAYS",
    "DEFAULT_PROVIDER_FLAGS",
]

DEFAULT_OUT_PATH = Path("docs/feed.xml")
DEFAULT_FEED_HEALTH_PATH = Path("docs/feed-health.md")
DEFAULT_FEED_HEALTH_JSON_PATH = Path("docs/feed-health.json")
DEFAULT_FEED_TITLE = "ÖPNV Störungen Wien & Umgebung"
DEFAULT_FEED_DESCRIPTION = "Aktive Störungen/Baustellen/Einschränkungen aus offiziellen Quellen"
DEFAULT_FEED_LINK = "https://github.com/Origamihase/wien-oepnv"
DEFAULT_FEED_TTL_MINUTES = 15
DEFAULT_DESCRIPTION_CHAR_LIMIT = 170
DEFAULT_FRESH_PUBDATE_WINDOW_MIN = 5
DEFAULT_MAX_ITEMS = 10
DEFAULT_MAX_ITEM_AGE_DAYS = 365
DEFAULT_ABSOLUTE_MAX_ITEM_AGE_DAYS = 540
DEFAULT_ENDS_AT_GRACE_MINUTES = 10
DEFAULT_CACHE_MAX_AGE_HOURS = 24
DEFAULT_PROVIDER_TIMEOUT = 25
DEFAULT_PROVIDER_MAX_WORKERS = 0
DEFAULT_STATE_PATH = Path("data/first_seen.json")
DEFAULT_STATE_RETENTION_DAYS = 60
DEFAULT_PROVIDER_FLAGS = {
    "WL_ENABLE": True,
    "OEBB_ENABLE": True,
    "VOR_ENABLE": True,
    "BAUSTELLEN_ENABLE": True,
}
