name: Reusable - Update VOR cache

on:
  workflow_call:

permissions:
  contents: write

concurrency:
  group: vor-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      VOR_ACCESS_ID: ${{ secrets.VOR_ACCESS_ID }}
      VOR_BASE_URL: ${{ secrets.VOR_BASE_URL }}
      VOR_BASE: ${{ secrets.VOR_BASE }}
      VOR_VERSION: ${{ secrets.VOR_VERSION }}
      PIP_CACHE_DIR: /tmp/pip-cache

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure pip cache directory exists
        run: mkdir -p "$PIP_CACHE_DIR"

      - name: Validate VOR secrets
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${VOR_ACCESS_ID:-}" || -z "${VOR_BASE_URL:-}" ]]; then
            echo "Secrets fehlen (VOR_ACCESS_ID/VOR_BASE_URL)." >&2
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Smoke test VOR
        shell: bash
        run: |
          set -euo pipefail
          base="${VOR_BASE_URL:-${VOR_BASE}/${VOR_VERSION}/}"
          code=$(curl -sS -o /dev/null -w "%{http_code}" -G \
            "${base}location.name" \
            --data-urlencode "input=Wien Hauptbahnhof" \
            --data-urlencode "format=json" \
            --data-urlencode "accessId=${VOR_ACCESS_ID}")
          echo "location.name -> HTTP ${code}"
          test "$code" = "200"

      - name: Refresh VOR cache
        run: python scripts/update_vor_cache.py

      - name: Commit and push changes
        if: ${{ github.ref_type == 'branch' }}
        shell: bash
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -f cache/vor/events.json ]]; then
            git add cache/vor/events.json
          fi

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          branch="${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
          git commit -m 'chore: update VOR cache'
          git pull --rebase origin "$branch"
          git push origin HEAD:"$branch"
