name: Reusable - Update Wiener Linien cache

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure pip cache directory exists
        run: mkdir -p "$PIP_CACHE_DIR"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Refresh Wiener Linien cache
        run: python scripts/update_wl_cache.py

      - name: Commit and push changes
        shell: bash
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cache/wl/events.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          branch="${BRANCH_NAME:-${GITHUB_REF#refs/heads/}}"
          if [[ -z "$branch" || "$branch" == "$GITHUB_REF" ]]; then
            branch="$(git rev-parse --abbrev-ref HEAD)"
          fi
          git commit -m 'chore: update Wiener Linien cache'
          git pull --rebase origin "$branch"
          git push origin HEAD:"$branch"
